name: pg-harness-client
version: "0.6.0"
synopsis: Client library for pg-harness-server.
description: >
  Client library for <https://hackage.haskell.org/package/pg-harness-server pg-harness-server>
  for conveniently creating temporary PostgreSQL databases for use in tests.
category: Database Testing Web
license: BSD2
license-file: LICENSE.txt
author: Bardur Arantsson
maintainer: bardur@scientician.net
copyright: Copyright (c) 2014-2020 Bardur Arantsson
github: BardurArantsson/pg-harness

ghc-options: -Wall

dependencies:
  - base == 4.*
  - bytestring >= 0.9.0.1
  - HTTP >= 4000.2.17 && < 4001

library:
  exposed-modules:
    - Database.PostgreSQL.Harness.Client
  source-dirs: src
